FROM node:20-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV NEXT_TELEMETRY_DISABLED 1
ENV PORT 3000

EXPOSE ${PORT}

CMD ["sh", "-c", "npm run dev -- -p ${PORT}"]
